# Generated by Django 4.2 on 2024-11-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='enquiry',
        ),
    ]
