services:
  web:
    build: .
    volumes:
      - .:/app
      - ./static:/app/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web