services:
  web:
    build: .
    volumes:
      - .:/app
      - ./cheonan/static:/app/staticfiles/cheonan
      - ./yangju/static:/app/staticfiles/yangju
      - ./cheongju/static:/app/staticfiles/cheongju
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cheonan/static:/app/staticfiles/cheonan
      - ./yangju/static:/app/staticfiles/yangju
      - ./cheongju/static:/app/staticfiles/cheongju
    ports:
      - "80:80"
    depends_on:
      - web