# Generated by Django 4.2 on 2025-02-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheonan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '천안고객'},
        ),
    ]
